CC=gcc
CFLAGS=-Wall -g

BUILD_SUF=-build

all: 1_1 1_2 2

1_1: 1_1.c
	$(CC) $(CFLAGS) -o 1_1$(BUILD_SUF) 1_1.c

1_2: 1_2.c
	$(CC) $(CFLAGS) -o 1_2$(BUILD_SUF) 1_2.c

2: 2.c
	$(CC) $(CFLAGS) -o 2$(BUILD_SUF) 2.c
